apiVersion: apps/v1
kind: Deployment
metadata:
  name: newstracker
  labels:
    app: newstracker
spec:
  selector:
    matchLabels:
      app: newstracker
  template:
    metadata:
      labels:
        app: newstracker
    spec:
      containers:
        - name: newstracker
          image: suryaprasaath/newstrackerapp:v1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "500Mi"
