name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: [ self-hosted, dockerbuilt ]
    steps:
    - uses: actions/checkout@v2
    - name: Switch to root
      run: sudo su
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag suryaprasaath/newstrackerapp:v1
    - name: Push the Docker image
      run: docker push suryaprasaath/newstrackerapp:v1
    - name: Clean up the Docker image
      run: docker rmi suryaprasaath/newstrackerapp:v1
    
