name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - 'Cloud_application/**'
      - 'README.md'
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: [ self-hosted, dockerbuilt ]
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag suryaprasaath/newstrackerapp:v1.${{ github.run_id }}
    - name: Push the Docker image
      run: sudo docker push suryaprasaath/newstrackerapp:v1.${{ github.run_id }}
    - name: Clean up the Docker image
      run: sudo docker rmi suryaprasaath/newstrackerapp:v1.${{ github.run_id }}
    
